import type { AnalysisMode, CfaoThresholds, StoreRecord } from "@/lib/cfao";
export type SkuPreset = { id:string; name:string; ourSku:string; competitorSkus:string[]; oneToOneMode:boolean; defaultMode:AnalysisMode; thresholds:CfaoThresholds; };
export type SavedRun = { id:string; label:string; month:string; presetId?:string; ourSku:string; competitorSkus:string[]; oneToOneMode:boolean; mode:AnalysisMode; thresholds:CfaoThresholds; createdAt:string; summary:{ cuts:number; fixes:number; adds:number; outperform:number; }; rows:StoreRecord[]; };
const PRESETS_KEY = "cfao-presets-v2";
const RUNS_KEY = "cfao-runs-v2";
export function defaultPresets(): SkuPreset[] { return [{ id:"2804B", name:"2804B Standard Bourbon", ourSku:"2804B", competitorSkus:["6539B","6931B","9520B"], oneToOneMode:false, defaultMode:"annual", thresholds:{ cutRetailMax:3, cutWholesaleMax:6, cutCraftAvgMax:15, fixCraftAvgMin:20, fixPctOfCraftAvg:0.5, addCraftAvgMin:20, outperformRetailMin:15 } }, { id:"3135B", name:"3135B House Vodka", ourSku:"3135B", competitorSkus:["7698B","9505B","6930B","4166B"], oneToOneMode:false, defaultMode:"annual", thresholds:{ cutRetailMax:3, cutWholesaleMax:6, cutCraftAvgMax:15, fixCraftAvgMin:20, fixPctOfCraftAvg:0.5, addCraftAvgMin:20, outperformRetailMin:15 } }, { id:"5656L", name:"5656L Capital City vs Vohio", ourSku:"5656L", competitorSkus:["9755L"], oneToOneMode:true, defaultMode:"annual", thresholds:{ cutRetailMax:3, cutWholesaleMax:6, cutCraftAvgMax:15, fixCraftAvgMin:20, fixPctOfCraftAvg:0.5, addCraftAvgMin:20, outperformRetailMin:15 } }]; }
export function loadPresets(): SkuPreset[] { if (typeof window === "undefined") return defaultPresets(); try { const raw = window.localStorage.getItem(PRESETS_KEY); if (!raw) return defaultPresets(); return JSON.parse(raw) as SkuPreset[]; } catch { return defaultPresets(); } }
export function savePresets(presets: SkuPreset[]) { if (typeof window === "undefined") return; window.localStorage.setItem(PRESETS_KEY, JSON.stringify(presets)); }
export function loadRuns(): SavedRun[] { if (typeof window === "undefined") return []; try { const raw = window.localStorage.getItem(RUNS_KEY); if (!raw) return []; return JSON.parse(raw) as SavedRun[]; } catch { return []; } }
export function saveRuns(runs: SavedRun[]) { if (typeof window === "undefined") return; window.localStorage.setItem(RUNS_KEY, JSON.stringify(runs)); }
